DROP SCHEMA public CASCADE;

DROP TABLE student IF EXISTS;
CREATE TABLE student (
  id_student INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  nr_indeksu VARCHAR(20) NOT NULL,
  pesel VARCHAR(11) NOT NULL,
  imie VARCHAR(30) NOT NULL,
  nazwisko VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL,
  login VARCHAR(30) NOT NULL,
  haslo VARCHAR(30) NOT NULL,
  adres VARCHAR(100) NOT NULL,
  rok_studiow INTEGER,
  CONSTRAINT duplikat_peselu_student UNIQUE (pesel),
  CONSTRAINT duplikat_indeksu_student UNIQUE (nr_indeksu),
  CONSTRAINT duplikat_loginu_student UNIQUE (login),
  CONSTRAINT duplikat_emaila_student UNIQUE (email)
  );

  DROP TABLE wykladowca IF EXISTS;
  CREATE TABLE wykladowca (
    id_wykladowca INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    imie VARCHAR(30) NOT NULL,
    nazwisko VARCHAR(30) NOT NULL,
    tytul_naukowy VARCHAR(50),
    email VARCHAR(50) NOT NULL,
    login VARCHAR(30) NOT NULL,
    haslo VARCHAR(30) NOT NULL,
    CONSTRAINT duplikat_loginu_wykladowca UNIQUE (login),
    CONSTRAINT duplikat_emaila_wykladowca UNIQUE (email)
  );

  DROP TABLE przedmiot IF EXISTS;
  CREATE TABLE przedmiot (
    id_przedmiot INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    nazwa VARCHAR(30) NOT NULL,
    ects INTEGER,
    semestr VARCHAR(10),
    opis VARCHAR(255),
    limit_miejsc INTEGER,
    CONSTRAINT duplikat_nazwa_przedmiot UNIQUE (nazwa)
  );

  DROP TABLE sylabus IF EXISTS;
  CREATE TABLE sylabus (
    id_sylabus INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    id_przedmiot INTEGER NOT NULL,
    nazwa VARCHAR(50),
    tresc VARCHAR(2000),
    FOREIGN KEY (id_przedmiot) REFERENCES przedmiot(id_przedmiot)
  );

  DROP TABLE plan_zajec IF EXISTS;
  CREATE TABLE plan_zajec (
    id_plan INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    id_przedmiot INTEGER NOT NULL,
    id_wykladowca INTEGER NOT NULL,
    dzien_tygodnia VARCHAR(15) NOT NULL,
    godzina_start TIME,
    godzina_koniec TIME,
    sala VARCHAR(10),
    typ VARCHAR(20),
    FOREIGN KEY (id_przedmiot) REFERENCES przedmiot(id_przedmiot),
    FOREIGN KEY (id_wykladowca) REFERENCES wykladowca(id_wykladowca)
  );

  DROP TABLE zapis IF EXISTS;
  CREATE TABLE zapis (
    id_zapis INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    id_student INTEGER NOT NULL,
    id_przedmiot INTEGER NOT NULL,
    data_zapisu DATE,
    rok_akademicki VARCHAR(20),
    status VARCHAR(30),
    FOREIGN KEY (id_student) REFERENCES student(id_student),
    FOREIGN KEY (id_przedmiot) REFERENCES przedmiot(id_przedmiot)
  );

  DROP TABLE ocena IF EXISTS;
  CREATE TABLE ocena (
    id_ocena INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    id_zapis INTEGER NOT NULL,
    wartosc DOUBLE,
    kategoria VARCHAR(20), --ocena cząstkowa lub końcowa
    komentarz VARCHAR(200),
    data_wystawienia DATE,
    FOREIGN KEY (id_zapis) REFERENCES zapis(id_zapis)
  );

  DROP TABLE ksiazka IF EXISTS;
  CREATE TABLE ksiazka (
    id_ksiazka INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    tytul VARCHAR(50),
    autor VARCHAR(100),
    isbn VARCHAR(40),
    ilosc INTEGER,
    dostepna BOOLEAN DEFAULT TRUE
  );

  DROP TABLE wypozyczenie IF EXISTS;
  CREATE TABLE wypozyczenie (
    id_wypozyczenie INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    id_student INTEGER NOT NULL,
    id_ksiazka INTEGER NOT NULL,
    data_wypozyczenia DATE,
    termin_zwrotu DATE,
    data_oddania DATE,
    status VARCHAR(20),
    FOREIGN KEY (id_student) REFERENCES student(id_student),
    FOREIGN KEY (id_ksiazka) REFERENCES ksiazka(id_ksiazka)
  );

  DROP TABLE platnosc IF EXISTS;
  CREATE TABLE platnosc (
    id_platnosc INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    id_student INTEGER NOT NULL,
    tytul VARCHAR(50) NOT NULL,
    kwota DOUBLE NOT NULL,
    opis VARCHAR(100),
    data_wplaty DATE,
    status VARCHAR(20),
    FOREIGN KEY (id_student) REFERENCES student(id_student)
  );

  DROP TABLE powiadomienie IF EXISTS;
  CREATE TABLE powiadomienie (
    id_powiadomienie INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    id_student INTEGER NOT NULL,
    tytul VARCHAR(100),
    tresc VARCHAR(1000),
    data_wyslania DATE,
    FOREIGN KEY (id_student) REFERENCES student(id_student)
  );