DROP SCHEMA public CASCADE;

DROP TABLE student IF EXISTS;
CREATE TABLE student (
  id_student INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  nr_indeksu VARCHAR(20) NOT NULL,
  pesel VARCHAR(11) NOT NULL,
  imie VARCHAR(30) NOT NULL,
  nazwisko VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL,
  login VARCHAR(30) NOT NULL,
  haslo VARCHAR(30) NOT NULL,
  adres VARCHAR(100) NOT NULL,
  rok_studiow INTEGER,
  CONSTRAINT duplikat_peselu UNIQUE (pesel),
  CONSTRAINT duplikat_indeksu UNIQUE (nr_indeksu),
  CONSTRAINT duplikat_loginu UNIQUE (login)
  );

  DROP TABLE wykladowca IF EXISTS;
  CREATE TABLE wykladowca (
    id_wykladowca INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    imie VARCHAR(30) NOT NULL,
    nazwisko VARCHAR(30) NOT NULL,
    tytul_naukowy VARCHAR(50),
    email VARCHAR(50) NOT NULL,
    login VARCHAR(30) NOT NULL,
    haslo VARCHAR(30) NOT NULL,
    CONSTRAINT duplikat_loginu UNIQUE (login)
  );